### PR TITLE
Add support for OCI registries

### PR DESCRIPTION
**Pull request by kubasobon**
Towards https://github.com/giantswarm/roadmap/issues/391

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by kubasobon** [comment]
@giantswarm/team-honeybadger PTAL. This is still pending a test, but the structure will overall stay the same.

**Review by MarcelMue — COMMENTED** [review]
Generally looks reasonable

**Comment by kubasobon** [comment]
Tested locally, pulling the chart works. I have a question or two to ask on the team's forum regarding some future-proofing of the design.

**Review by rossf7 — COMMENTED** [review]
Nice job 👍  and I like the comments adding extra context.

**Review by rossf7 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
