### PR TITLE
Upgrade helm to v3.8.1

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR upgrades helm to 3.8.1

I ran `go mod tidy`

## Checklist

- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by rossf7 — COMMENTED** [review]
@ubergesundheit Thanks for this. We need to test it by upgrading chart-operator. I'll be working on that this week.

**Comment by ubergesundheit** [comment]
Thank you <3

Feel free to re-use this PR or how I could be more helpful :)

**Comment by rossf7** [comment]
@ubergesundheit OK if we close this in favor of #402 that @kubasobon is working on?

**Comment by ubergesundheit** [comment]
Totally fine :)

**Pull request closed without merging**
